# Generated by Django 4.2.19 on 2025-02-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.IntegerField(unique=True)),
                ('problem_title', models.CharField(max_length=255)),
                ('last_viewed', models.DateField(auto_now=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('problem_pattern', models.TextField()),
                ('solution_approach', models.TextField()),
            ],
        ),
    ]
